### ISSUE TITLE
Using this without shortcode

### ISSUE THREAD

**Issue by nimeso** [TheBnl/silverstripe-instagram#1]
I have a Class called ContentBlockInstagram.php which has a 'has_one relashionship' with the main Page.php class. It is rendered using ContentBlockInstagram.ss

How do I get images without using the shortcode? I basically just want to hard code it in the template?

I hope that makes sense?

**Comment by TheBnl** [comment]
Hi Nimeso,

Are you able to run the `ImportMediaTasks` trough cron?
Because then you would be able to just query the `InstagramMediaObject` trough you `ContentBlockInstagram`.

For example getting the latest instagram post:
```php
public function getLatestInstagramPost()
{
    return InstagramMediaObject::get()->first();
}
```

Otherwise you could use the `Instagram` class to get posts directly from the Instagram API:
```php
$instagram = Instagram::create();
// get's an ArrayList from the first member that is authenticated with the Instagram client
$media = $instagram->getCurrentUserMedia($limit = null);
```
